version: '3'
services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: ngi
    ports:
      - "80:80"
    volumes:
      - "/Users/hmoubal/Desktop/inception/srcs/requirements/nginx/conf:/etc/nginx/http.d"
