version: '3'
services:


  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - mynetwork
    depends_on:
      - mariadb
    volumes:
      - "/Users/hmoubal/Desktop/inception/srcs/requirements/nginx/conf:/etc/nginx/sites-available"
      - wp:/var/www/html




  wordpress:
    image: wordpress
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    container_name: wordpress
    networks:
      - mynetwork
    restart: always
    env_file:
      - ./.env
    depends_on:
      - mariadb 
      - nginx
    volumes:
      - wp:/var/www/html



  mariadb:
    image: mariadb 
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    container_name: mariadb
    env_file:
      - ./.env
    networks:
      - mynetwork
    restart: always
    volumes:
      - db:/var/lib/mysql



networks:
  mynetwork:
    driver: bridge    

volumes:
  wp:
    driver_opts:
      device: /Users/hmoubal/Desktop/inception/wordpress
      o: bind
      type: none
  db:
    driver_opts:
      device: /Users/hmoubal/Desktop/inception/mariadb
      o: bind
      type: none