version: '3'
services:


  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "8080:80"
    restart: always
    networks:
      - mynetwork
    depends_on:
      - mariadb
      - adminer
    volumes:
      - "/Users/hmoubal/Desktop/inception/srcs/requirements/nginx/conf:/etc/nginx/sites-available"
      - wp:/var/www/html
      - adminer:/var/www/adminer




  wordpress:
    image: wordpress
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    container_name: wordpress
    networks:
      - mynetwork
    restart: always
    env_file:
      - ./.env
    depends_on:
      - mariadb 
      - redis
    volumes:
      - wp:/var/www/html



  mariadb:
    image: mariadb 
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    container_name: mariadb
    env_file:
      - ./.env
    networks:
      - mynetwork
    restart: always
    volumes:
      - db:/var/lib/mysql


  redis:
    image: redis
    build:
      context: ./
      dockerfile: ./requirements/bonus/redis/Dockerfile
    container_name: redis
    restart: always
    networks:
      - mynetwork

  adminer:
    image: adminer
    build:
      context: ./
      dockerfile: ./requirements/bonus/adminer/Dockerfile
    container_name: adminer
    restart: always
    networks:
      - mynetwork
    volumes:
      - adminer:/var/www/adminer

  ftp:
    image: ftp
    build:
      context: ./
      dockerfile: ./requirements/bonus/ftp/Dockerfile
    container_name: ftp
    restart: always
    depends_on:
      - wordpress
    ports:
      - "101:21"
      - "102:20"
    networks:
      - mynetwork
    volumes:
      - wp:/var/www/html


networks:
  mynetwork:
    driver: bridge    

volumes:
  wp:
    driver_opts:
      device: /Users/hmoubal/Desktop/inception/wordpress
      o: bind
      type: none
  db:
    driver_opts:
      device: /Users/hmoubal/Desktop/inception/mariadb
      o: bind
      type: none
  adminer:
    driver_opts:
      device: /Users/hmoubal/Desktop/inception/adminer
      o: bind
      type: none