version: '3'
services:


  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: ngi
    ports:
      - "80:443"
    restart: always
    networks:
      - mynetwork
    depends_on:
      - wordpress
    volumes:
      - "/Users/hmoubal/Desktop/inception/srcs/requirements/nginx/conf:/etc/nginx/sites-available"
      - data:/var/www/html




  wordpress:
    image: wordpress
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    container_name: wp
    networks:
      - mynetwork
    restart: always
    env_file:
      - ./.env
    depends_on:
      - mariadb 
    volumes:
      - data:/var/www/html



  mariadb:
    image: mariadb 
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    container_name: db
    env_file:
      - ./.env
    networks:
      - mynetwork
    restart: always
    # volumes:
    #   - "Users/hmoubal/Desktop/inception/srcs/requirements/mariadb/conf:/etc/mysql/conf.d"



networks:
  mynetwork:
    driver: bridge    

volumes:
  data: